sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.4
  - 2.3.7
  - 2.2.10
before_install:
  - gem update --system
  - gem update --remote bundler
gemfile:
  - gemfiles/mail_2.5.gemfile
  - gemfiles/mail_2.6.gemfile
  - gemfiles/mail_2.7.gemfile
